### ISSUE TITLE
Publish the API on a maven repository

### ISSUE THREAD

**Issue by tlaundal** [CheeseSoftware/PowerfulPermsAPI#1]
Hi,

Having the plugin published to an external maven repository would make it much more convenient when including it as an dependency for a maven project.

Something like oss.sonatype.org would be great, if not, spigot or another existing Minecraft related repository could work. Even a repo just for this would be better than nothing.

Thanks!

**Comment by gustav9797** [comment]
http://repo.alskebo.com/
