### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by SequaciousGAMES** [CheeseSoftware/PowerfulPermsAPI#3]
**Edited to Amend Already Implemented Features**
- A command to add a group to all existing users, if they already have it, do nothing.
- A placeholder that functions similarly to;
'{powerfulperms_firstprefix_<ladder 1>_<ladder 2>_<ladder 3 etc>}'
but would instead be;
'{powerfulperms_prefixes_<ladder 1>_<ladder 2>_<ladder 3 etc>}'
This would display ALL prefixes of the defined groups instead of just the first one. For example, '{powerfulperms_prefixes_Donator_Default}' would show as [http://prntscr.com/dt8flv](http://prntscr.com/dt8flv)
This would eliminate the need to use a heck of a lot of placeholders on servers with lots of ranks.

**Comment by BruurTycho** [comment]
Agree with Tab Complete

**Comment by gustav9797** [comment]
Tab completion finished for PowerfulPerms v4.4.0.

**Comment by SequaciousGAMES** [comment]
Anything on the other features?

**Comment by gustav9797** [comment]
Having /pp user 'name' setrank 'groupname' auto add a user to a ladder if they're not on it already.

That is done too. Nothing else.

**Comment by SequaciousGAMES** [comment]
May I ask why not the others?

**Comment by gustav9797** [comment]
I implement one thing at a time.
