### ISSUE TITLE
CaseInsensitive World and Server permissions

### ISSUE THREAD

**Issue by Kraeutergarten** [CheeseSoftware/PowerfulPermsAPI#5]
Currently permissions have to have the correct case for server and world names. 
May you can add caseinsensitive for this.

Hopefully you understand what i mean.

essentials.fly main newfreebuild (does not work)
essentials.fly main NewFreebuild (does work)

Thanks

**Comment by Kraeutergarten** [comment]
What do you think about that?

**Comment by Kraeutergarten** [comment]
I would welcome your response @gustav9797

**Comment by gustav9797** [comment]
Sorry for the delay.
~~Server and world names in permission and group entries are entirely case insensitive.~~
Looking into this.

**Comment by Kraeutergarten** [comment]
Okay, so there is a bug correct ?
Because i testet it again is see there is a case sensitivity

I think the error is in permissionApplies

```
(paramPermission.getServer().equals(paramString1))
(paramPermission.getWorld().equals(paramString2))
```

May you can release a fast Bug update?
@gustav9797

**Comment by gustav9797** [comment]
Yes, it's fixed. Message me on Skype and I will send you the new version later.
