### ISSUE TITLE
BungeeCord Postlogin Event (Issue)

### ISSUE THREAD

**Issue by Kraeutergarten** [CheeseSoftware/PowerfulPermsAPI#8]
I had some listener which promotes players on postlogin event.
For some reasons p.haspermission always was false. 
I think thats was caused that you load cached data on EventPriority.LOW which was the same as my listener. Maybe you should load data on Byte.MIN_VALUE

**Comment by gustav9797** [comment]
EventPriority.LOW runs before higher priorities because it has lower priority to change the final outcome. Which priority do you use?
Try using the ServerConnectedEvent.

**Comment by Kraeutergarten** [comment]
Im was using also LOW. So there was a Problem. 
Maybe you can use "Byte.MIN_VALUE" that your dataloading isn't on a "default" Priority and loads at first.
